replicaCount: 10

productionSlot: blue

blue:
  enabled: true
  tag: latest

green:
  enabled: true
  tag: latest

image:
  repository: xcreuwcyan.azurecr.io/cyanserver
  pullPolicy: IfNotPresent

imagePullSecrets: []

serviceAccount:
  create: true
  name:

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true

  hostName: 51.105.197.234.nip.io
  
  annotations: 
    kubernetes.io/ingress.class: azure/application-gateway
    
  hosts:
    - backend:
        serviceName: cyan-api-server
        servicePort: 3000
