apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: server-agic
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: cyan-api-server
          servicePort: 3000