trigger: none

resources:
- repo: self

stages:
- stage: Deploy
  displayName: Deploy Go client app

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'MarkWmecyan.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self