trigger: none

resources:
- repo: self

variables:
- group: cyan
- name: vmImageName
  value: 'ubuntu-latest'
- name: something
  value: format('Hello {0} {1}', 'John', $(aks_resource_group))

stages:
- stage: Deploy
  displayName: Deploy Go client app

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -x
          env
          echo $AKS_RESOURCEGROUP
          echo $SOMETHING
          az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
          helm upgrade --install -n $KUBERNETES_NAMESPACE $HELM_RELEASE_NAME_PRODUCTION deploy/charts/client-go --set apiServerURL=$api_server_url_production --reuse-values
          helm upgrade --install -n $kubernetes_namespace $helm_release_name_staging deploy/charts/client-go --set apiServerURL=$api_server_url_staging --reuse-values