trigger: none

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Deploy Go client app

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'MarkWmecyan.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Microsoft Azure(808121c2-95b0-4e15-8dbc-cb6de76a956a)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -x
                az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
                helm install -n $KUBERNETES_NAMESPACE $HELM_RELEASE_NAME_PRODUCTION deploy/charts/client-go --set apiServerURL=$API_SERVER_URL_PRODUCTION
                helm install -n $KUBERNETES_NAMESPACE $HELM_RELEASE_NAME_STAGING deploy/charts/client-go --set apiServerURL=$API_SERVER_URL_STAGING

