trigger: none

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Deploy to Staging

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'MarkWmecyan.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Microsoft Azure(808121c2-95b0-4e15-8dbc-cb6de76a956a)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -x
                az aks get-credentials -g x-rg-euw-aks-cyan -n x-ks-euw-cyan
                productionSlot=$(helm get values cyan-api-server | awk '/productionSlot/{print $2}')
                if [ $productionSlot == "blue" ]; then
                    stagingSlot="green"
                else
                    stagingSlot="blue"
                fi
                helm upgrade cyan-api-server deploy/charts/server --set $stagingSlot.enabled=true,$stagingSlot.tag=$STAGINGTAG --reuse-values
