trigger: none

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Deploy to Canary

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'MarkWmecyan.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Microsoft Azure(808121c2-95b0-4e15-8dbc-cb6de76a956a)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -x
                az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
                #
                # Check if already deployed. If so, we can upgrade, if not we need
                # to install fresh. We don't use the --install option for a Helm
                # upgrade as if we're installing fresh we need to define some user
                # values - specifically, the productionSlot value needs to be
                # specifically set
                #
                helm upgrade -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-api-server deploy/charts/server-canary --set ingress.canary=true,ingress.canaryweight=$CANARY_WEIGHT --reuse-values
