trigger: none

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Setup Staging Blue / Green Environment

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'MarkWmecyan.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -x
                az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
                helm uninstall -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-api-server
                helm uninstall -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-client-go-nginx-production
                helm uninstall -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-client-go-nginx-staging
                helm uninstall -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-client-go-agic-production
                helm uninstall -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-client-go-agic-staging
