{{ if .Values.green.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}-green
  labels:
    {{- include "server.labels" . | nindent 4 }}
    slot: green
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
      slot: green
  template:
    metadata:
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
        slot: green
    spec:
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.green.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/getVersion
              port: http
          readinessProbe:
            httpGet:
              path: /api/getVersion
              port: http

{{ end }}