{{- if .Values.ingress.enabled -}}
{{- $fullName := include "server.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-production
  labels:
    {{- include "server.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: 51.105.197.234.nip.io
    http:
      paths:
      - backend:
          serviceName: {{ $fullName }}-production
          servicePort: {{ $svcPort }}
{{- end }}
