#
# Setup environment for demonstrating canary deployments
# using nginx canary annotations.
#
trigger: none

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Deploy to Canary

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'MarkWmecyan.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmInstaller@1
            inputs:
              helmVersionToInstall: 'latest'
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Microsoft Azure(808121c2-95b0-4e15-8dbc-cb6de76a956a)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                set -x
                az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
                #
                # Get current production slot value, then configure the
                # script to deploy to the other slot
                #                
                productionSlot=$(helm get values -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-api-server | awk '/productionSlot/{print $2}')
                if [ $productionSlot == "blue" ]; then
                    canarySlot="green"
                else
                    canarySlot="blue"
                fi
                helm upgrade -n $KUBERNETES_NAMESPACE ${HELM_RELEASE_NAME_STUB}-api-server deploy/charts/server-canary --set $canarySlot.enabled=true,$canarySlot.tag=$CANARY_TAG --reuse-values
